-- Seed DEV only — UPSERT inventory
BEGIN;
INSERT INTO nl_agentes_inventario (agent_id,name,role_or_function,entity_id,status,maturity_q,owner,git_manifest_path,version,notes) VALUES ('nl-code-reviewer','nl-code-reviewer','code-reviewer','nortiqa-lab','approved-staging','Q2','gio','.github/agents/code-reviewer.agent.md','1.1.0','lab acceptance harness v1.1') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, version=EXCLUDED.version, updated_at=now();
INSERT INTO nl_agentes_inventario (agent_id,name,role_or_function,entity_id,status,maturity_q,owner,git_manifest_path,version,notes) VALUES ('nl-database-migrator','nl-database-migrator','database-migrator','nortiqa-lab','approved-staging','Q2','gio','.github/agents/database-migrator.agent.md','1.1.0','lab acceptance harness v1.1') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, version=EXCLUDED.version, updated_at=now();
INSERT INTO nl_agentes_inventario (agent_id,name,role_or_function,entity_id,status,maturity_q,owner,git_manifest_path,version,notes) VALUES ('nl-implementer','nl-implementer','implementer','nortiqa-lab','approved-staging','Q2','gio','.github/agents/implementer.agent.md','1.1.0','lab acceptance harness v1.1') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, version=EXCLUDED.version, updated_at=now();
INSERT INTO nl_agentes_inventario (agent_id,name,role_or_function,entity_id,status,maturity_q,owner,git_manifest_path,version,notes) VALUES ('nl-inspector','nl-inspector','inspector','nortiqa-lab','approved-staging','Q2','gio','.github/agents/inspector.agent.md','1.1.0','lab acceptance harness v1.1') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, version=EXCLUDED.version, updated_at=now();
INSERT INTO nl_agentes_inventario (agent_id,name,role_or_function,entity_id,status,maturity_q,owner,git_manifest_path,version,notes) VALUES ('nl-security-reviewer','nl-security-reviewer','security-reviewer','nortiqa-lab','approved-staging','Q2','gio','.github/agents/security-reviewer.agent.md','1.1.0','lab acceptance harness v1.1') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, version=EXCLUDED.version, updated_at=now();
INSERT INTO nl_agentes_inventario (agent_id,name,role_or_function,entity_id,status,maturity_q,owner,git_manifest_path,version,notes) VALUES ('nl-tester','nl-tester','tester','nortiqa-lab','approved-staging','Q2','gio','.github/agents/tester.agent.md','1.1.0','lab acceptance harness v1.1') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, version=EXCLUDED.version, updated_at=now();
INSERT INTO nl_agentes_inventario (agent_id,name,entity_id,status,maturity_q,owner,notion_url,notes) VALUES ('AGENTE-GASTRO-001','Agente de Pedidos Rotisería','nortiqa-lab','diseño','Q1','Gio + Claude','https://app.notion.com/p/393e4fe3bfea8113aa15ec1356427e3e','from INDICE-NL-AGENTES-PROYECTOS-001 2026-07-10') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, notion_url=EXCLUDED.notion_url, updated_at=now();
INSERT INTO nl_agentes_inventario (agent_id,name,entity_id,status,maturity_q,owner,notion_url,notes) VALUES ('NL-ID-AG-001','Agente Director I+D','nortiqa-lab','activo','Q3','Gio','https://app.notion.com/p/350e4fe3bfea81c3ac80d13c9248655a','from INDICE-NL-AGENTES-PROYECTOS-001 2026-07-10') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, notion_url=EXCLUDED.notion_url, updated_at=now();
INSERT INTO nl_agentes_inventario (agent_id,name,entity_id,status,maturity_q,owner,notion_url,notes) VALUES ('ANL-EST-001','Agente Management Económico-Financiero','nortiqa-lab','borrador','Q0','Gio','https://app.notion.com/p/34ee4fe3bfea81c1b0f6dc0d733b2e8e','from INDICE-NL-AGENTES-PROYECTOS-001 2026-07-10') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, notion_url=EXCLUDED.notion_url, updated_at=now();
INSERT INTO nl_agentes_inventario (agent_id,name,entity_id,status,maturity_q,owner,notion_url,notes) VALUES ('PRM-NL-AUT-001','Nortiqa Desktop Operator','nortiqa-lab','activo','Q3','Codex','https://app.notion.com/p/37ee4fe3bfea8135aed8f3614db1c54c','from INDICE-NL-AGENTES-PROYECTOS-001 2026-07-10') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, notion_url=EXCLUDED.notion_url, updated_at=now();
INSERT INTO nl_agentes_inventario (agent_id,name,entity_id,status,maturity_q,owner,notion_url,notes) VALUES ('BOT-012','Bot Nocturno de Avance Conceptual','nortiqa-lab','aprobado-condicional','Q2','Gio','https://app.notion.com/p/34ee4fe3bfea81f7b604eb8d09c4fcb8','from INDICE-NL-AGENTES-PROYECTOS-001 2026-07-10') ON CONFLICT (agent_id) DO UPDATE SET status=EXCLUDED.status, notion_url=EXCLUDED.notion_url, updated_at=now();
INSERT INTO nl_tareas (task_id,title,entity_id,status,priority,assignee,notion_url,definition_of_done) VALUES ('TASK-NL-STORAGE-001','Migracion hibrida almacenamiento Fase 0 seed','nortiqa-lab','in_progress',1,'NL-BUILDER','https://app.notion.com/p/3b0e4fe3bfea81c6acc2e485bdcf6558','Seed governance+SQL listo; sin borrar Notion; sin PROD') ON CONFLICT (task_id) DO UPDATE SET status=EXCLUDED.status, updated_at=now();
COMMIT;
